openapi: 3.1.0 # <1>
info:
  title: Webhook API
  description: |
    **Warning:** Responses from destination services other than 2XX status code are treated as failed webhook integration, indicating that the webhook request was not acknowledged.
  version: v1
webhooks: # <2>
  dummy.event: # <2>
    post: # <2>
      summary: Dummy event created in source service
      description: Description of a request that may be initiated by the source service (API provider) and expected responses from the destination service.
      parameters: # <3>
        - $ref: '#/components/parameters/WebhookId'
        - $ref: '#/components/parameters/WebhookSignature'
        - $ref: '#/components/parameters/WebhookTimestamp'
      requestBody: # <4>
        $ref: '#/components/requestBodies/Event'
      responses: # <5>
        200:
          $ref: '#/components/responses/OK'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
components:
  parameters: # <3>
    WebhookId:
      name: Webhook-Id
      in: header
      required: true
      schema:
        type: string
    WebhookSignature:
      name: Webhook-Signature
      in: header
      required: true
      schema:
        type: string
    WebhookTimestamp:
      name: Webhook-Timestamp
      in: header
      required: true
      schema:
        type: string
  requestBodies: # 4
    Event:
      description: Event's JSON payload
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Event'
          examples:
            dummy.event:
              value:
                type: dummy.event
                timestamp: 1709111631
                data:
                  echo: test
  responses: # <5>
    OK:
      description: OK - Webhook was received by the destination service
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Event' # <6>
    BadRequest:
      description: BadRequest - Webhook was not acknowledged by the the destination service
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized - Webhook was not acknowledged by the the destination service
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas: # <6>
      Event:
        type: object
        properties:
          type:
            type: string
            description: The type of the event
          timestamp:
            type: string
            description: The timestamp of the event
          data:
            type: object
            description: The data associated with the event
      Error:
        type: object
        properties:
          errors:
            type: array
            description: The error message!
            items:
              type: string
