from rest_framework.status import HTTP_200_OK

from core.www import swagger_rest_schema_view
from tests.setup import SetupTestCase


class OpenAPIRestSchemaTest(SetupTestCase):

    def setUp(self):
        super().setUp()
        self.view = swagger_rest_schema_view

    def test_rest_schema_autogenerated(self):
        request = self.factory.get("docs/api/v1/schema/auto")
        response = self.view(request)

        self.assertEqual(response.status_code, HTTP_200_OK)

    def test_rest_schema_manualy_created_v1(self):
        request = self.factory.get("docs/api/v1/schema/manual")
        response = self.view(request)

        self.assertEqual(response.status_code, HTTP_200_OK)

    def test_rest_schema_manualy_created_latest(self):
        request = self.factory.get("docs/api/v1/schema/manual/latest")
        response = self.view(request)

        self.assertEqual(response.status_code, HTTP_200_OK)

    def test_docs_swagger_ui(self):
        request = self.factory.get("docs/api/v1")
        response = self.view(request)

        self.assertEqual(response.status_code, HTTP_200_OK)
