# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enricher/proto/enricher/v1/enricher.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'enricher/proto/enricher/v1/enricher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)enricher/proto/enricher/v1/enricher.proto\x12\x0b\x65nricher.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n\x04\x43ity\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\"\xe9\x01\n\x0fWeatherForecast\x12\x1f\n\x04\x63ity\x18\x01 \x01(\x0b\x32\x11.enricher.v1.City\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0brain_sum_mm\x18\x03 \x01(\x01\x12\x16\n\x0eshowers_sum_mm\x18\x04 \x01(\x01\x12\x17\n\x0fsnowfall_sum_cm\x18\x05 \x01(\x01\x12\x1f\n\x17temperature_max_celsius\x18\x06 \x01(\x01\x12\x1f\n\x17temperature_min_celsius\x18\x07 \x01(\x01\"G\n\rEnrichRequest\x12\x36\n\x10weather_forecast\x18\x01 \x01(\x0b\x32\x1c.enricher.v1.WeatherForecast\"!\n\x0e\x45nrichResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2T\n\x0f\x45nricherService\x12\x41\n\x06\x45nrich\x12\x1a.enricher.v1.EnrichRequest\x1a\x1b.enricher.v1.EnrichResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enricher.proto.enricher.v1.enricher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CITY']._serialized_start=91
  _globals['_CITY']._serialized_end=158
  _globals['_WEATHERFORECAST']._serialized_start=161
  _globals['_WEATHERFORECAST']._serialized_end=394
  _globals['_ENRICHREQUEST']._serialized_start=396
  _globals['_ENRICHREQUEST']._serialized_end=467
  _globals['_ENRICHRESPONSE']._serialized_start=469
  _globals['_ENRICHRESPONSE']._serialized_end=502
  _globals['_ENRICHERSERVICE']._serialized_start=504
  _globals['_ENRICHERSERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
